18 code of conduct
cscareerhub/csch-web pull request #19
Opened 2021-04-06 12:50 UTC by ianvln

Added a code of conduct page with. Content was copy-pasted from a Google result.

I chose to go for the implementation using MDX template pages. If I need to update something, let me know!

2021-04-09 02:19 UTC, sirNikolai commented on next.config.js
> +  })
nl

2021-04-09 02:19 UTC, sirNikolai commented on src/pages/code-of-conduct.mdx
> +[INSERT CONTACT METHOD].
@brendacs I guess this would be server channel?

2021-04-09 03:38 UTC, brendacs commented on src/pages/code-of-conduct.mdx
> +[INSERT CONTACT METHOD].
Linking to https://cscareerhub.com/contact would actually be better

2021-04-09 03:40 UTC, brendacs requested changes
I would prefer the code of conduct to be from our Discord server's rules in the #welcome channel. I'm also ok with having two - one for server rules and one for this code of conduct

2021-04-09 03:48 UTC, brendacs commented
Great job with this! And MDX was a good choice. Just one other comment - make sure to use the `stage` branch as the base instead of `master`.

2021-04-10 10:59 UTC, ianvln commented on next.config.js
> +  })
nl? 😄

2021-04-10 11:13 UTC, ianvln commented
> I would prefer the code of conduct to be from our Discord server's rules in the #welcome channel. I'm also ok with having two - one for server rules and one for this code of conduct

I've added a separate page for the server rules

2021-04-10 17:38 UTC, brendacs commented on next.config.js
> +  })
It means new line

2021-04-21 05:41 UTC, brendacs approved these changes
looks great!

2021-04-21 05:41 UTC, merged